# Generated by Django 3.2 on 2023-07-04 19:19

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('pp', models.ImageField(upload_to=services.uploader.Uploader.upload_menu_to_restaurants)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('won_country', models.CharField(max_length=200)),
                ('won_city', models.CharField(max_length=200)),
                ('won_university', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=200)),
                ('scholarship', models.BooleanField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
