# Generated by Django 3.2 on 2023-07-07 09:50

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('photo', models.ImageField(upload_to=services.uploader.Uploader.upload_photo_for_blog)),
                ('head', models.CharField(max_length=255)),
                ('main_part', models.TextField()),
            ],
            options={
                'verbose_name': 'Bloq',
                'verbose_name_plural': 'Bloqlar',
                'ordering': ('-created_at',),
            },
        ),
    ]
