# Generated by Django 3.2 on 2023-07-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0003_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='meet_date',
            field=models.DateTimeField(),
        ),
    ]
