# Generated by Django 3.2 on 2023-07-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0004_alter_consultation_meet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='education_degree',
            field=models.CharField(blank=True, choices=[('Orta təhsil', 'Orta təhsil'), ('Bakalavr', 'Bakalavr'), ('Magistratura', 'Magistratura')], default='Bakalavr', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='interest_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='interested_scholarship_programs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='is_met',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='language_certificate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='meet_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='meet_type',
            field=models.CharField(blank=True, choices=[('Phone Call', 'Phone Call'), ('Google Meet', 'Google Meet'), ('Offline', 'Offline')], default='Offline', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='work_experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
